sudo: required
dist: trusty
language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake .. -DMEZZ_BuildDoxygen=OFF

# yes is just an application that returns true, this means perform no installation
install: yes

script: make

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  ./StaticFoundation_Tester MEZZ_BuildDoxygen:0 MEZZ_Linux:1 MEZZ_BuildStaticLibraries:1 MEZZ_MacOSX:0 MEZZ_Windows:0 MEZZ_CompilerDesignNix:1 MEZZ_CompilerDesignMS:0 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  ./StaticFoundation_Tester MEZZ_BuildDoxygen:0 MEZZ_Linux:0 MEZZ_BuildStaticLibraries:1 MEZZ_MacOSX:1 MEZZ_Windows:0 MEZZ_CompilerDesignNix:1 MEZZ_CompilerDesignMS:0 ; fi

notifications:
  email:
    recipients:
      - contact@blacktoppstudios.com
    on_success: change
    on_failure: always
