version: 0.0.{build}
clone_folder: C:\projects\Mezz_StaticFoundation

environment:
  matrix:
  - GENERATOR: MinGW Makefiles
    CompilerPath: C:\msys64\mingw32\bin
    CompilerMS: "0"
    CompilerNix: "1"
  - GENERATOR: MinGW Makefiles
    CompilerPath: C:\msys64\mingw64\bin
    CompilerMS: "0"
    CompilerNix: "1"
#  - GENERATOR: Visual Studio 14 2015
#    CompilerMS: "1"
#    CompilerNix: "0"
  - GENERATOR: Visual Studio 14 2015 Win64
    CompilerMS: "1"
    CompilerNix: "0"

configuration:
  - Debug
  - Release
  
before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files (x86)\Git\usr\bin;=%
  # Move the non-mingw-w64 install to the end of the PATH
  - set PATH=%PATH:C:\MinGW\bin;=%
  # Ensure the appropriate install is in the PATH
  - set PATH=%CompilerPath%;%PATH%
  # Finalize build prep
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% .. -DMEZZ_BuildDoxygen=OFF

build_script:
  - cmake --build . --config %CONFIGURATION%
  
test_script:
  - cmd: cd C:\projects\Mezz_StaticFoundation\build
  - if ["%GENERATOR%"] != ["MinGW Makefiles"] ( cmd: cd %configuration% )
  - cmd: StaticFoundation_Tester MEZZ_BuildDoxygen:0 MEZZ_Linux:0 MEZZ_BuildStaticLibraries:1 MEZZ_MacOSX:0 MEZZ_Windows:1 MEZZ_CompilerDesignNix:%CompilerNix% MEZZ_CompilerDesignMS:%CompilerMS%

notifications:
- provider: Email
  to:
  - contact@blacktoppstudios.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
  
